---
- hosts: CSR1
  gather_facts: false
  connection: local
  tasks:
  - name: Configure G2
    ios_config:
      lines:
      - ipp addr 30.30.30.30 255.255.255.0
      - description somethinghere
      - no shut
      parents: interface Gigabit2
  - name: Name Devices
    ios_config:
      lines:
      - hostname CSRone1
  - name: Disable Domain-lookup
      ios_command:
        commands:
        - no ip domain-lookup
  - name: Password Setup
      ios_config:
        lines:
        - security passwords min-length 10 #Require 10 character passwords
        - service password-encryption #Encrypt al plaintext passwords
    - name: Banner Setup
      ios_config:
        lines:
        - banner motd $Warning! Words here!$ #Configure banner 
