---
- hosts: web1
  gather_facts: no
  tasks:
  - name: Test copy file to web1
    ansible.builtin.copy:
      src: /home/justincase/git/IT385/IT385py/week8/inventory.txt
      dest: /home/justincase/file1.txt