---
- hosts: routers
  gather_facts: false
  connection: local
  tasks:
  - name: Get config
    ios_command:
      commands: show run | exclude ! 
    register: output_router
  
  - name: Save config
    copy:
      content: "{{ output_config }}"
      dest: "/home/justincase/git/IT385/IT385py/week9/runConf{{ inventory_hostname }}.txt"