---
- hosts: web
  gather_facts: yes
  tasks:
  - name: Report facts
    ansible.builtin.debug:
      var: ansible_facts["uptime_seconds"]
    when: ansible_facts["uptime_seconds"] > 600
  - name: Reboot (not nice)
    become: yes
    reboot:
    when: ansible_facts["uptime_seconds"] > 600