---
- hosts: web
  gather_facts: yes
  tasks:
  - name: Find time
    ansible.builtin.debug:
      var: ansible_facts["uptime_seconds"]
  - name: Nice reboot
    become: yes
    reboot:
    when: ansible_facts["uptime_seconds"] > 600