---
- hosts: routers
  gather_facts: false
  connection: local
  tasks:
  - name: Default Route setup
    ios_command:
      commands: 
      - conf t
      - line con 0
      - password GRCCon
      - login
      - end