#!usr/bin/env python3

import random

def guess_function():
    r_2 = int(input("Enter the highest desired range to guess from, from 1 to "))
    tries = int(input("How many tries do you want?\n"))
    n=0
    r_n = random.randint(1, r_2)
    while (tries >= 0):
        if n != r_n:
            tries = tries - 1
            n= int(input("Whats your guess?\n"))
            if n < r_n:
                print("Higher")
            elif n > r_n:
                print("Lower")
            elif n == r_n:
                print("Thats Correct! You had ", tries, " tries left.")
                tries_left = tries
                tries = 0
                print(tries)
                print(tries_left)
                pass
            pass
        pass
    pass


guess_function()
print("end")
replay_q = int(input("Do you wish to play again (1), move to the next level (2), \n see leaderboard (3), or quit (4)"))
if (replay_q == 1):
        guess_function
else:
        print("Goodbye")